notifier:
    messages:
      - 'A MESSAGE'
    enabled: true
    chat_id: <CHAT_ID>
    token: <TOKEN>
providers:
    provider_a:
        base_url: <URL>
        sources:
          - <PATH>
database:
    store: '<localsqlite|herokupg>'
    # Option exclusive to herokupg store 
    heroku_app_name: '<APP_NAME>' 